# Generated by Django 3.0.5 on 2022-05-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Two wheeler with Gear', 'Two wheeler with Gear'), ('Two wheeler without Gear', 'Two wheeler without Gear'), ('Three wheeler', 'Three wheeler'), ('Four wheeler', 'Four wheeler')], max_length=50),
        ),
    ]
