# Generated by Django 3.0.5 on 2022-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20220508_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emergency',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/CustomerProfilePic/'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/MechanicProfilePic/'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='skill',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Repairing', 'Repairing'), ('Repairing Done', 'Repairing Done'), ('Released', 'Released')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(max_length=10),
        ),
    ]
