# Generated by Django 3.0.5 on 2022-05-12 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20220512_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('[A-Za-z]')]),
        ),
    ]
